name: CI

on:
  push:
    branches: [ CI/CD ]

jobs:

  create_or_update_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: pulumi-up
        uses: pulumi/actions@v1
        with: 
          command: up
        env: 
          PULUMI_ROOT: infrastructure 
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  checkout_branch_and_build_a_project:      
    runs-on: ubuntu-latest
    steps:
      - name: checkout-branch
        uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build-project
        env:
          CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
          CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
          MAILCHIMP_ENDPOINT: 'https://www.gatsbyjs.org/packages/gatsby-plugin-mailchimp/?=mailchimp#mailchimp-endpoint'
        run: |
          npm ci
          npm run build           