name: CI/CD

on:
  push:
    branches: [ CI/CD ]

jobs:

  create_or_update_infrastructure-and-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-branch
        uses: actions/checkout@v2
      - name: pulumi-up
        uses: pulumi/actions@v1
        with: 
          command: up
        env: 
          PULUMI_ROOT: infrastructure 
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build-project
        env:
          CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
          CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
          MAILCHIMP_ENDPOINT: 'https://www.gatsbyjs.org/packages/gatsby-plugin-mailchimp/?=mailchimp#mailchimp-endpoint'
        run: |
          npm ci
          npm run build           
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy
        uses: jonelantha/gatsby-s3-action@v1
        with:
          dest-s3-bucket: static-website-alpacked-63fd8b0
          cloudfront-id-to-invalidate: EY8ECBK3RDLKW